// Compile DTCG (2025.10) token files to CSS custom properties. Themes override the
// base set; aliases ("{group.token}") are resolved per theme. Output is committed
// and checked in CI (`pnpm gen:check`).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const THEMES = ["light", "dark", "high-contrast"];
const load = (name) => JSON.parse(readFileSync(here(`./tokens/${name}.tokens.json`), "utf8"));

function flatten(group, path = [], inheritedType, out = {}) {
  const type = group.$type ?? inheritedType;
  for (const [key, node] of Object.entries(group)) {
    if (key.startsWith("$")) continue;
    if (node && typeof node === "object" && "$value" in node) {
      out[[...path, key].join(".")] = { type: node.$type ?? type, value: node.$value };
    } else if (node && typeof node === "object") {
      flatten(node, [...path, key], type, out);
    }
  }
  return out;
}

function resolve(tokens, name, seen = new Set()) {
  const token = tokens[name];
  if (!token) throw new Error(`unknown token ${name}`);
  if (typeof token.value === "string" && /^\{[^}]+\}$/.test(token.value)) {
    const ref = token.value.slice(1, -1);
    if (seen.has(ref)) throw new Error(`alias cycle at ${name}`);
    return resolve(tokens, ref, new Set([...seen, name]));
  }
  return token;
}

function cssValue({ type, value }) {
  if (type === "dimension") return `${value.value}${value.unit}`;
  if (type === "fontFamily") return value.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(", ");
  return String(value);
}

const varName = (name) => `--ea-${name.replaceAll(".", "-")}`;
const base = flatten(load("base"));
const resolved = {};
let css = "/* Generated by packages/tokens/build.mjs from DTCG sources. Do not edit. */\n";
for (const theme of THEMES) {
  const tokens = theme === "light" ? base : { ...base, ...flatten(load(theme)) };
  const names = Object.keys(tokens).filter((n) => !n.startsWith("palette."));
  resolved[theme] = Object.fromEntries(names.map((n) => [n, cssValue(resolve(tokens, n))]));
  const selector =
    theme === "light"
      ? ':root, :host, [data-theme="light"], :host([data-theme="light"])'
      : `[data-theme="${theme}"], :host([data-theme="${theme}"])`;
  const body = names.map((n) => `  ${varName(n)}: ${resolved[theme][n]};`).join("\n");
  css += `${selector} {\n${body}\n}\n`;
}
writeFileSync(here("./src/generated/tokens.css"), css);
writeFileSync(here("./src/generated/tokens.json"), `${JSON.stringify(resolved, null, 2)}\n`);
