/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/local/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local Session */
        post: operations["local_session_v1_local_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_v1_runs__run_id__approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/approvals/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending */
        get: operations["pending_v1_runs__run_id__approvals_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_v1_runs__run_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile */
        post: operations["reconcile_v1_runs__run_id__reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description Resume from ``Last-Event-ID`` (automatic reconnect) or ``after_sequence``
         *     (a new EventSource after a snapshot, which cannot set headers).
         */
        get: operations["stream_v1_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Accepted */
        Accepted: {
            /**
             * Status
             * @constant
             */
            status: "accepted";
        };
        /**
         * ActionState
         * @enum {string}
         */
        ActionState: "PROPOSED" | "VALIDATED" | "BLOCKED" | "AWAITING_APPROVAL" | "APPROVED" | "RESERVED" | "DISPATCHING" | "COMMITTED" | "FAILED" | "UNKNOWN" | "VERIFIED" | "VERIFICATION_FAILED";
        /** ActionSummary */
        ActionSummary: {
            /** Action Id */
            action_id: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Contract Id */
            contract_id: string;
            state: components["schemas"]["ActionState"];
        };
        /**
         * ApprovalPresentation
         * @description Everything any UI needs to show an approval; the digest input is included verbatim.
         */
        ApprovalPresentation: {
            /** Action Id */
            action_id: string;
            /** Binding Id */
            binding_id: string;
            /** Canonical Proposal */
            canonical_proposal: {
                [key: string]: unknown;
            };
            /** Connection Id */
            connection_id: string;
            /** Contract Id */
            contract_id: string;
            /** Credential Subject */
            credential_subject: string;
            /** Digest */
            digest: string;
            /** Expires At */
            expires_at: string;
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Material Fields */
            material_fields: components["schemas"]["MaterialField"][];
            /** Run Id */
            run_id: string;
            /** Run Revision */
            run_revision: number;
        };
        /** CreateRun */
        CreateRun: {
            host_context?: components["schemas"]["HostContext"] | null;
            /** Task */
            task: string;
        };
        /** CreateRunResponse */
        CreateRunResponse: {
            /** Created */
            created: boolean;
            /** Run Id */
            run_id: string;
        };
        /** Decide */
        Decide: {
            /** Action Id */
            action_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Digest */
            digest: string;
            /** Expected Revision */
            expected_revision: number;
        };
        /** Finding */
        Finding: {
            /**
             * Evidence Ids
             * @default []
             */
            evidence_ids: string[];
            /** Expected */
            expected?: string | null;
            /** Message */
            message: string;
            /** Observed */
            observed?: string | null;
            /** Rule Id */
            rule_id: string;
            /** Rule Version */
            rule_version: string;
            status: components["schemas"]["ValidationStatus"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HostContext
         * @description Provider-neutral, untrusted hints from an embedding host (UI architecture §4.7).
         */
        HostContext: {
            /**
             * Host Kind
             * @enum {string}
             */
            host_kind: "standalone" | "embedded";
            /** Locale */
            locale?: string | null;
            /** Page Url Origin */
            page_url_origin?: string | null;
            /**
             * Resource Hints
             * @default []
             */
            resource_hints: components["schemas"]["ResourceHint"][];
            /** Selection Text */
            selection_text?: string | null;
        };
        /** MaterialField */
        MaterialField: {
            /**
             * Changed
             * @default false
             */
            changed: boolean;
            /** Path */
            path: string;
            /** Previous Value */
            previous_value?: string | null;
            /** Value */
            value: string;
        };
        /**
         * ResourceHint
         * @description What a host page says the user is looking at. Untrusted; never grants access.
         */
        ResourceHint: {
            /** External Id Hint */
            external_id_hint: string;
            /** Resource Type Hint */
            resource_type_hint: string;
            /** System Hint */
            system_hint: string;
        };
        /** RunEvent */
        RunEvent: {
            /** Action Id */
            action_id?: string | null;
            /** Correlation Id */
            correlation_id?: string | null;
            /** Event Id */
            event_id: string;
            /** Occurred At */
            occurred_at: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: string;
            /** Sequence */
            sequence: number;
            /** Tenant Id */
            tenant_id: string;
            type: components["schemas"]["RunEventType"];
        };
        /**
         * RunEventType
         * @enum {string}
         */
        RunEventType: "run.created" | "run.state_changed" | "read.recorded" | "proposal.created" | "validation.completed" | "approval.requested" | "approval.decided" | "connect.required" | "input.requested" | "input.received" | "action.reserved" | "action.dispatching" | "action.receipt_recorded" | "action.unknown" | "reconciliation.completed" | "outcome.reported" | "message.final" | "budget.exhausted" | "run.cancel_requested" | "run.terminal";
        /** RunRecord */
        RunRecord: {
            /** Created At */
            created_at: string;
            /** Logical Operation Id */
            logical_operation_id: string;
            /** Reason */
            reason?: string | null;
            /** Requester Id */
            requester_id: string;
            /** Revision */
            revision: number;
            /** Run Id */
            run_id: string;
            state: components["schemas"]["RunState"];
            /** Task */
            task: string;
            /** Tenant Id */
            tenant_id: string;
        };
        /** RunSnapshot */
        RunSnapshot: {
            /** Actions */
            actions: components["schemas"]["ActionSummary"][];
            /** Latest Sequence */
            latest_sequence: number;
            pending_approval: components["schemas"]["ApprovalPresentation"] | null;
            run: components["schemas"]["RunRecord"];
        };
        /**
         * RunState
         * @enum {string}
         */
        RunState: "CREATED" | "RUNNING" | "WAITING_INPUT" | "WAITING_APPROVAL" | "VERIFYING" | "NEEDS_RECONCILIATION" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        /** SessionResponse */
        SessionResponse: {
            /** Csrf Token */
            csrf_token: string;
            /** Principal */
            principal: string;
            /** Tenant */
            tenant: string;
        };
        /** StateResponse */
        StateResponse: {
            state: components["schemas"]["RunState"];
            /**
             * Unresolved
             * @default false
             */
            unresolved: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationStatus
         * @enum {string}
         */
        ValidationStatus: "PASS" | "FAIL" | "UNKNOWN" | "ERROR";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    local_session_v1_local_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    create_run_v1_runs_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRun"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_v1_runs__run_id__approvals_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decide"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pending_v1_runs__run_id__approvals_pending_get: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalPresentation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                after_sequence?: number;
            };
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_v1_runs__run_id__evidence_get: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconcile_v1_runs__run_id__reconcile_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_v1_runs__run_id__stream_get: {
        parameters: {
            query?: {
                after_sequence?: number;
            };
            header?: {
                "last-event-id"?: string | null;
                "x-csrf-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
